[package]
authors = ["jD91mZM2 <me@krake.one>"]
description = "SSL without a certificate authority"
license-file = "LICENSE"
name = "sslhash"
repository = "https://github.com/jD91mZM2/sslhash"
version = "0.1.1"
[dependencies]
failure = "0.1.1"
openssl = "0.10.2"
